### ISSUE TITLE
Duplicate name on monument

### ISSUE THREAD

**Issue by chrismore** [mozilla/mozmonument-sf#1]
For example, the following name shows up three times, but it is the same person.
- Frederic Wenzel
- Fred Wenzel
- Frédéric Wenzel

As a first pass on de-duping the names, we can find duplicate last names or do some regex magic on the file to find duplicate sub-strings.

**Comment by twse** [comment]
Here's some examples of more names.
- Jim Chen
- Jim Ningjie Chen
- Jim Ningjie Chen
- William Chen
- William Alexander Chen
- Ying ui Lora Chen
- Yingui Chen
- Wei-Ko Kao
- Wei-Ko Kao
