### ISSUE TITLE
Encoding OOPS on the monument

### ISSUE THREAD

**Issue by k5e** [mozilla/mozmonument-sf#2]
There is a name that got mangled by some encoding going wrong:
![OOPS](https://f.cloud.github.com/assets/606885/2049252/cb97c97a-8a5c-11e3-8c59-cd9b68fc226b.png)

``` json
{
 "side": "1",
 "panel": "lower",
 "row": "47",
 "number": "6",
 "name": "Arda Ã‡aÄŸlayaner" 
}
```

**Comment by fwenzel** [comment]
"Nice". I am impressed my name showed up right.

**Comment by LouCypher** [comment]
> I am impressed my name showed up right.

@fwenzel [Three times](../issues/1).

**Comment by fwenzel** [comment]
Fair. Though only one spelling (i.e., the right one) has the potential for encoding errors ;)

**Comment by twse** [comment]
Looks fine in my mock up with all names printed with the Purista font on Scribus:
![duplicate](https://user-images.githubusercontent.com/2715694/33076537-5152534a-cf10-11e7-9010-ee460bd579c5.png)

**Moderator's note:** The Purista font can be used to print the names in the monument, however Mozilla cannot use this for legal reasons.
