### ISSUE TITLE
Incorrect Vietnamese names

### ISSUE THREAD

**Issue by 1ec5** [mozilla/mozmonument-sf#3]
@vuhung is listed as “Hung Nguyen Vu”. His name should be written “Nguyễn Vũ Hưng”.

@train255 is listed as “Dang Duy Thanh” in Vietnamese order, so his name should ideally have diacritics: “Đặng Duy Thanh”.

**Comment by vuhung** [comment]
@1ec5 :100: I could not find my name in the PDF file :)

**Comment by 1ec5** [comment]
Search for “hung” in [this tool](http://thewebrocks.com/demos/mozilla-monument-name-finder/). The PDF isn’t entirely encoded in Unicode.
