### ISSUE TITLE
missing Tr team names possible add 

### ISSUE THREAD

**Issue by nadiraltinbas** [mozilla/mozmonument-sf#5]
is it possible to add names to M.Monument from Tr team contributers because of less members Tr are available over mozmonument ??nadir altinbas

**Comment by twse** [comment]
Hi Nadir, here's a partial list of contributors.
* Arman Aksoy
* Şâkir Aşçı
* Görkem Çetin
* Erdem Çobanoğlu
* Ali Demirtaş
* Ismail Murat Dilek
* Cem Elhasan
* Ersin Er
* Halil İbrahim Erdemir
* Tarkan Erimer
* Görkem Geleçek
* Salih Giray
* Erkan Kaplan
* Mert Salih Kaplan
* Halil Kaya
* Huseyin Killic
* Mert Nalçacı
* Huzeyfe Önal
* Murat Özalp
* Ilnar Salimzianov
* Serdar Soydemir
* Omer Timer
* Murat Unger

**Comment by nadiraltinbas** [comment]
Hi good day Tae-Woong Se, 

please see updated list at the following link; 

pontoon.mozilla.org/tr/contributors/ 

13-07-2018 19:11, Tae-Woong Se yazmış: 

> Hi Nadir, here's a partial list of contributors. 
> 
> * Arman Aksoy
> * Şâkir Aşçı
> * Görkem Çetin
> * Erdem Çobanoğlu
> * Ali Demirtaş
> * Ismail Murat Dilek
> * Cem Elhasan
> * Ersin Er
> * Halil İbrahim Erdemir
> * Tarkan Erimer
> * Görkem Geleçek
> * Salih Giray
> * Erkan Kaplan
> * Mert Salih Kaplan
> * Halil Kaya
> * Huseyin Killic
> * Mert Nalçacı
> * Huzeyfe Önal
> * Murat Özalp
> * Ilnar Salimzianov
> * Serdar Soydemir
> * Omer Timer
> * Murat Unger
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/mozilla/mozmonument-sf/issues/5#issuecomment-404879740
[2]
